#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

DRY_RUN=0
WITH_MCP=1
WITH_OMX=1
SKIP_SKILLS=0
DEFAULT_MODEL_CMD='["codex","--search","exec","--skip-git-repo-check"]'
MODEL_CMD="${PAPERO_MODEL_CMD:-$DEFAULT_MODEL_CMD}"
ENV_FILE="$ROOT/.paperorchestra.env"

usage() {
  cat <<'USAGE'
PaperOrchestra installer

Usage:
  ./install.sh [--skip-skills] [--skip-mcp] [--skip-omx] [--dry-run]

What it does by default:
  - creates .venv if needed
  - installs PaperOrchestra into .venv
  - installs all bundled Codex skills into ~/.codex/skills
  - writes a generic PAPERO_MODEL_CMD into .paperorchestra.env
  - registers the PaperOrchestra MCP server for Codex CLI
  - runs omx setup when omx is available
  - prints the restart/check command

Options:
  --mcp          compatibility no-op: MCP registration is already on by default
  --skip-mcp     skip Codex MCP registration
  --skip-omx     skip omx setup even when omx is available
  --skip-skills  skip Codex skill installation
  --dry-run      print the plan without changing files
  -h, --help     show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mcp) WITH_MCP=1 ;;
    --skip-mcp|--no-mcp) WITH_MCP=0 ;;
    --skip-omx|--no-omx) WITH_OMX=0 ;;
    --skip-skills) SKIP_SKILLS=1 ;;
    --dry-run) DRY_RUN=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

find_python() {
  if [[ -n "${PYTHON:-}" ]]; then
    printf '%s\n' "$PYTHON"
    return 0
  fi
  if command -v python3 >/dev/null 2>&1; then
    command -v python3
    return 0
  fi
  if command -v python >/dev/null 2>&1; then
    command -v python
    return 0
  fi
  echo "Python 3.11+ is required but no python3/python was found on PATH." >&2
  return 1
}

print_step() {
  printf '\n==> %s\n' "$1"
}

run() {
  printf '+ '
  printf '%q ' "$@"
  printf '\n'
  if [[ "$DRY_RUN" -eq 0 ]]; then
    "$@"
  fi
}

write_provider_env() {
  {
    printf '# Generated by ./install.sh.\n'
    printf '# Override PAPERO_MODEL_CMD before running install.sh if you prefer a different shell provider.\n'
    printf 'export PAPERO_MODEL_CMD=%q\n' "$MODEL_CMD"
  } > "$ENV_FILE"
}

PYTHON_BIN="$(find_python)"
INSTALL_TARGET="."

printf 'PaperOrchestra installer\n'
printf 'Repository: %s\n' "$ROOT"
if [[ "$DRY_RUN" -eq 1 ]]; then
  printf 'Mode: dry-run\n'
fi

print_step "Create local virtualenv"
echo "plan: python -m venv .venv"
if [[ ! -x "$ROOT/.venv/bin/python" ]]; then
  run "$PYTHON_BIN" -m venv "$ROOT/.venv"
else
  echo "+ .venv already exists"
fi

print_step "Install package"
echo "plan: pip install -e '$INSTALL_TARGET'"
run "$ROOT/.venv/bin/python" -m pip install -e "$INSTALL_TARGET"

if [[ "$SKIP_SKILLS" -eq 0 ]]; then
  print_step "Install Codex skills"
  echo "plan: scripts/install-skill.sh"
  run bash "$ROOT/scripts/install-skill.sh"
else
  print_step "Skip Codex skills"
fi

print_step "Configure model command"
echo "plan: write .paperorchestra.env"
echo "plan: PAPERO_MODEL_CMD=$MODEL_CMD"
if [[ "$DRY_RUN" -eq 0 ]]; then
  write_provider_env
fi

if [[ "$WITH_MCP" -eq 1 ]]; then
  print_step "Register Codex MCP server"
  echo "plan: scripts/register-codex-mcp.sh --use-local-venv"
  run bash "$ROOT/scripts/register-codex-mcp.sh" --use-local-venv --provider-command "$MODEL_CMD"
else
  print_step "Skip Codex MCP registration"
fi

if [[ "$WITH_OMX" -eq 1 ]]; then
  print_step "Enable OMX integration"
  echo "plan: omx setup (if omx is available)"
  if command -v omx >/dev/null 2>&1; then
    run omx setup
  else
    echo "+ omx not found; skipping"
  fi
else
  print_step "Skip OMX setup"
fi

cat <<EOF_NEXT

Next:
  .venv/bin/paperorchestra status --json

Optional:
  ./install.sh --skip-mcp  # install without Codex MCP registration
  ./install.sh --skip-omx  # install without running omx setup

Restart Codex/OMX after installation so MCP tools reload. S2 is optional.
EOF_NEXT
