from __future__ import annotations

from paperorchestra.runtime.environment_spec import EnvironmentVariableSpec


SHELL_PROVIDER_VARIABLES: tuple[EnvironmentVariableSpec, ...] = (
    EnvironmentVariableSpec(
        name='PAPERO_MODEL_CMD',
        category='shell_provider',
        operator_settable=True,
        default=None,
        example='["codex","--search","exec","--skip-git-repo-check"]',
        description='Shell-provider command: reads prompt from stdin and writes response to stdout.',
        required_for=('shell_provider_ready', 'full_live_run_ready', 'claim_safe_full_run_ready'),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_TIMEOUT_SECONDS',
        category='shell_provider',
        operator_settable=True,
        default='unset',
        example='600',
        description='Timeout for shell-provider model calls.',
        required_for=(),
        notes=('Optional unless your provider is slow.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_TIMEOUT_GRACE_SECONDS',
        category='shell_provider',
        operator_settable=True,
        default='0',
        example='120',
        description='Additional wait after the shell provider soft timeout before killing the process; useful when Codex reconnects and may recover without replay.',
        required_for=(),
        notes=('Set with PAPERO_PROVIDER_RETRY_ATTEMPTS for unstable Codex connections.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_RETRY_ATTEMPTS',
        category='shell_provider',
        operator_settable=True,
        default='0',
        example='2',
        description='Replay the same shell-provider prompt only after retryable transport evidence such as Codex reconnect/disconnect stderr; plain timeouts are grace-only and are not replayed.',
        required_for=(),
        notes=('Requires PAPERO_PROVIDER_RETRY_SAFE=1; keep disabled when an outer wrapper already owns retries.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_RETRY_BACKOFF_SECONDS',
        category='shell_provider',
        operator_settable=True,
        default='2',
        example='15',
        description='Sleep between retryable shell-provider prompt replays.',
        required_for=(),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_RETRY_JITTER_SECONDS',
        category='shell_provider',
        operator_settable=True,
        default='0',
        example='3',
        description='Optional random jitter added to provider retry backoff to avoid lockstep replays.',
        required_for=(),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_RETRY_SAFE',
        category='shell_provider',
        operator_settable=True,
        default='0',
        example='1',
        description='Declare that the shell-provider command is safe to replay after transport evidence; required before prompt replay is attempted.',
        required_for=(),
        notes=('Do not enable for provider commands with non-idempotent side effects.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_RETRY_TRACE_DIR',
        category='shell_provider',
        operator_settable=True,
        default='unset',
        example='review/provider-retry-traces',
        description='Optional directory where shell-provider retry/grace attempt metadata is written as JSONL.',
        required_for=(),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_SEED',
        category='shell_provider',
        operator_settable=True,
        default='unset',
        example='7',
        description='Optional seed passthrough for shell-provider subprocesses; downstream commands must explicitly honor it.',
        required_for=(),
        notes=('Advanced reproducibility knob; PaperOrchestra forwards it but cannot force the model command to obey it.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_TEMPERATURE',
        category='shell_provider',
        operator_settable=True,
        default='unset',
        example='0.2',
        description='Optional temperature passthrough for shell-provider subprocesses.',
        required_for=(),
        notes=('Advanced quality/reproducibility knob; depends on downstream command support.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_PROVIDER_MAX_OUTPUT_TOKENS',
        category='shell_provider',
        operator_settable=True,
        default='unset',
        example='4096',
        description='Optional max-output-tokens passthrough for shell-provider subprocesses.',
        required_for=(),
        notes=('Advanced safety/latency knob; depends on downstream command support.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_ALLOWED_PROVIDER_BINARIES',
        category='shell_provider',
        operator_settable=True,
        default='codex,openai,ollama,llm,claude,gemini',
        example='codex,openai,ollama,llm,claude,gemini',
        description='Allowlist for shell-provider executables.',
        required_for=(),
        notes=('Only needed when using a custom provider executable.',),
    ),
)

__all__ = ["SHELL_PROVIDER_VARIABLES"]
