from __future__ import annotations

from paperorchestra.runtime.environment_spec import EnvironmentVariableSpec


CORE_RUNTIME_VARIABLES: tuple[EnvironmentVariableSpec, ...] = (
    EnvironmentVariableSpec(
        name='PAPERO_OMX_MODEL',
        category='core_runtime',
        operator_settable=True,
        default='Codex/OMX config',
        example='your-preferred-model',
        description='Optionally pass an explicit OMX-native model for PaperOrchestra stages.',
        required_for=(),
        notes=("Unset by default so Codex/OMX can use the operator's configured model.",),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_REASONING_EFFORT',
        category='core_runtime',
        operator_settable=True,
        default='Codex/OMX config',
        example='xhigh',
        description='Optionally pass an explicit OMX-native reasoning effort for live runs.',
        required_for=(),
        notes=("Unset by default so Codex/OMX can use the operator's configured effort.",),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_EXEC_TIMEOUT_SECONDS',
        category='core_runtime',
        operator_settable=True,
        default='bounded in code',
        example='900',
        description='Increase OMX exec timeout for slower live stages.',
        required_for=(),
        notes=('Optional; most useful for long live runs.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_CONTROL_TIMEOUT_SECONDS',
        category='core_runtime',
        operator_settable=True,
        default='60',
        example='120',
        description='Timeout for OMX control-plane calls such as `omx status`, `omx state`, and `omx explore`.',
        required_for=(),
        notes=('Optional; protects PaperOrchestra from hanging on stalled OMX control commands.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_STRICT_OMX_NATIVE',
        category='core_runtime',
        operator_settable=True,
        default='0',
        example='1',
        description='Fail instead of silently falling back from OMX-native stages when a claim-safe live run matters.',
        required_for=('claim_safe_full_run_ready',),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_REFINE_AXIS_TOLERANCE',
        category='core_runtime',
        operator_settable=True,
        default='0',
        example='2',
        description='Maximum allowed per-axis reviewer-score drop when refinement is otherwise non-regressive.',
        required_for=(),
        notes=('Advanced review-gate knob; lower values are stricter.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_STRICT_CONTENT_GATES',
        category='core_runtime',
        operator_settable=True,
        default='0',
        example='1',
        description='Promote selected content warnings to reproducibility BLOCK for claim-safe/review-ready runs.',
        required_for=('claim_safe_full_run_ready',),
        notes=('Currently blocks unsupported comparative claims and severe figure-placement warnings such as tail_clump.', 'Default draft mode remains warning-oriented.'),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_LATEX_TIMEOUT_SEC',
        category='core_runtime',
        operator_settable=True,
        default='30',
        example='120',
        description='Timeout in seconds for each sandboxed LaTeX/BibTeX command; valid range is 1-3600.',
        required_for=(),
        notes=('Useful for larger papers or slower CI/sandboxed TeX environments.',),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_DOMAIN',
        category='core_runtime',
        operator_settable=True,
        default='generic',
        example='generic',
        description='Select a registered deterministic writing/checking domain profile.',
        required_for=(),
        notes=('The public package bundles only the domain-neutral generic profile.', 'External plugins must call paperorchestra.domains.register_domain() before importing modules that cache domain fields.', 'Unknown profile names fail closed instead of silently falling back.'),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_TIMEOUT_GRACE_SECONDS',
        category='core_runtime',
        operator_settable=True,
        default='0',
        example='120',
        description='Additional wait after OMX soft timeouts before killing the process; applies to retryable read-like control calls and grace-only OMX exec calls.',
        required_for=(),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_RETRY_ATTEMPTS',
        category='core_runtime',
        operator_settable=True,
        default='0',
        example='1',
        description='Replay retryable read-only OMX control calls after reconnect-like transport failures; OMX exec is grace-only and is never replayed.',
        required_for=(),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_RETRY_BACKOFF_SECONDS',
        category='core_runtime',
        operator_settable=True,
        default='2',
        example='15',
        description='Sleep between retryable OMX-native call replays.',
        required_for=(),
        notes=(),
    ),
    EnvironmentVariableSpec(
        name='PAPERO_OMX_RETRY_JITTER_SECONDS',
        category='core_runtime',
        operator_settable=True,
        default='0',
        example='3',
        description='Optional random jitter added to OMX control retry backoff to avoid lockstep replays.',
        required_for=(),
        notes=(),
    ),
)

__all__ = ["CORE_RUNTIME_VARIABLES"]
