from __future__ import annotations


def _apply_mock_watermark(latex: str, state, provider_name: str | None = None) -> str:
    name = provider_name or state.latest_provider_name
    if name != "mock" and state.latest_verify_mode != "mock" and state.latest_verify_fallback_used != "mock":
        return latex
    marker = "DO NOT DISTRIBUTE AS A FACTUAL DRAFT."
    if marker in latex:
        return latex
    banner = (
        "% ============================================================\n"
        "% This manuscript was generated by PaperOrchestra with:\n"
        f"%   provider={state.latest_provider_name or provider_name or 'unknown'}    verify-mode={state.latest_verify_mode or 'unknown'}    runtime-mode={state.latest_runtime_mode or 'unknown'}\n"
        f"%   session-id={state.session_id}    timestamp={state.updated_at or state.created_at}\n"
        "% DO NOT DISTRIBUTE AS A FACTUAL DRAFT.\n"
        "% ============================================================\n"
    )
    if r"\documentclass" in latex:
        return latex.replace(r"\documentclass", banner + r"\documentclass", 1)
    return banner + latex


def _append_unique_note(state, note: str, *, dedupe_window: int = 5) -> bool:
    if not note:
        return False
    if note in state.notes[-dedupe_window:]:
        return False
    state.notes.append(note)
    return True

