from __future__ import annotations

from paperorchestra.engine.research_registry_merge import (
    merge_authoritative_external_ids,
    merge_live_verified_with_prior_registry,
    merge_verified_entry_with_prior_keys,
    normalized_registry_title_key,
    prior_work_metadata_is_authoritative,
)
from paperorchestra.engine.research_registry_payloads import citation_map_from_registry, registry_entry_payload

_registry_entry_payload = registry_entry_payload
_merge_live_verified_with_prior_registry = merge_live_verified_with_prior_registry
_normalized_registry_title_key = normalized_registry_title_key
_merge_verified_entry_with_prior_keys = merge_verified_entry_with_prior_keys
_prior_work_metadata_is_authoritative = prior_work_metadata_is_authoritative
_merge_authoritative_external_ids = merge_authoritative_external_ids
_citation_map_from_registry = citation_map_from_registry
